/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package educover;

import educover.backend.RecordAccess;
import educover.backend.UserSession;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author aizik
 */
public class AdminHomePage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminHomePage.class.getName());
    private static final String AccessLogFilePath = "src/educover/Data/Access_Log.txt";


  
    /**
     * Creates new form HomePage
     */
    public AdminHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        viewCourse = new javax.swing.JButton();
        addRecommendation = new javax.swing.JButton();
        eligibilityCheck = new javax.swing.JButton();
        viewProfile = new javax.swing.JButton();
        manageUsers = new javax.swing.JButton();
        updateRecommendation = new javax.swing.JButton();
        generateReport = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("homePage");

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        MainPanel.setPreferredSize(new java.awt.Dimension(1920, 1080));

        viewCourse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage_icons/open-book.png"))); // NOI18N
        viewCourse.setText("View Course");
        viewCourse.setAlignmentX(0.5F);
        viewCourse.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        viewCourse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewCourse.setPreferredSize(new java.awt.Dimension(100, 100));
        viewCourse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        viewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCourseActionPerformed(evt);
            }
        });

        addRecommendation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addRecommendation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage_icons/tumbUp.png"))); // NOI18N
        addRecommendation.setText("Add Recommendation");
        addRecommendation.setAlignmentX(0.5F);
        addRecommendation.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addRecommendation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addRecommendation.setPreferredSize(new java.awt.Dimension(100, 100));
        addRecommendation.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addRecommendation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecommendationActionPerformed(evt);
            }
        });

        eligibilityCheck.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        eligibilityCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage_icons/list.png"))); // NOI18N
        eligibilityCheck.setText("Eligibility Check");
        eligibilityCheck.setAlignmentX(0.5F);
        eligibilityCheck.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eligibilityCheck.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eligibilityCheck.setPreferredSize(new java.awt.Dimension(100, 100));
        eligibilityCheck.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eligibilityCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eligibilityCheckActionPerformed(evt);
            }
        });

        viewProfile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage_icons/user.png"))); // NOI18N
        viewProfile.setText("View Profile");
        viewProfile.setAlignmentX(0.5F);
        viewProfile.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        viewProfile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewProfile.setPreferredSize(new java.awt.Dimension(100, 100));
        viewProfile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        viewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfileActionPerformed(evt);
            }
        });

        manageUsers.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        manageUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage_icons/management.png"))); // NOI18N
        manageUsers.setText("Manage Users");
        manageUsers.setActionCommand("Manage Users");
        manageUsers.setAlignmentX(0.5F);
        manageUsers.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        manageUsers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        manageUsers.setPreferredSize(new java.awt.Dimension(100, 100));
        manageUsers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        manageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUsersActionPerformed(evt);
            }
        });

        updateRecommendation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updateRecommendation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage_icons/edit.png"))); // NOI18N
        updateRecommendation.setText("Update Recommendation");
        updateRecommendation.setAlignmentX(0.5F);
        updateRecommendation.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        updateRecommendation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        updateRecommendation.setPreferredSize(new java.awt.Dimension(100, 100));
        updateRecommendation.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        updateRecommendation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRecommendationActionPerformed(evt);
            }
        });

        generateReport.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        generateReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage_icons/report.png"))); // NOI18N
        generateReport.setText("Generate Report");
        generateReport.setAlignmentX(0.5F);
        generateReport.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        generateReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        generateReport.setPreferredSize(new java.awt.Dimension(100, 100));
        generateReport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        generateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage_icons/logout.png"))); // NOI18N
        logout.setText("Logout");
        logout.setAlignmentX(0.5F);
        logout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logout.setPreferredSize(new java.awt.Dimension(100, 100));
        logout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Admin Dashboard");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Welcome back. Select an option below to manage your courses and students.");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(manageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(150, 150, 150)
                                .addComponent(updateRecommendation, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(viewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(150, 150, 150)
                                .addComponent(addRecommendation, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(150, 150, 150)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eligibilityCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(150, 150, 150)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(viewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(235, 235, 235))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(147, 147, 147)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addRecommendation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eligibilityCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateRecommendation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(248, 248, 248))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1078, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewCourseActionPerformed

    private void manageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageUsersActionPerformed

    private void updateRecommendationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRecommendationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateRecommendationActionPerformed

    private void generateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportActionPerformed
            PerformanceReport check = new PerformanceReport();
            check.setVisible(true);
            check.setExtendedState(JFrame.MAXIMIZED_BOTH);
            this.dispose();
             
    }//GEN-LAST:event_generateReportActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        String [] result = RecordAccess.writeAccesslogs();
        

        if (result[0].equals("ERROR_LOGGING_OUT")){
            JOptionPane.showMessageDialog(this, "System Error", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JOptionPane.showMessageDialog(this, "Logout Successful ;)");
        UserSession.userID = "";
        UserSession.userName = "";
        UserSession.loginTime = "";
        LoginPage login = new LoginPage();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void addRecommendationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecommendationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addRecommendationActionPerformed

    private void eligibilityCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eligibilityCheckActionPerformed
            EligibilityCheck check = new EligibilityCheck(); 
            check.setVisible(true);
            check.setExtendedState(JFrame.MAXIMIZED_BOTH);
            this.dispose();
    }//GEN-LAST:event_eligibilityCheckActionPerformed

    private void viewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfileActionPerformed
        EditProfile profile = new EditProfile();
        profile.setVisible(true);
        profile.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_viewProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminHomePage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton addRecommendation;
    private javax.swing.JButton eligibilityCheck;
    private javax.swing.JButton generateReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logout;
    private javax.swing.JButton manageUsers;
    private javax.swing.JButton updateRecommendation;
    private javax.swing.JButton viewCourse;
    private javax.swing.JButton viewProfile;
    // End of variables declaration//GEN-END:variables
}
