/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package educover;
import javax.swing.*;
import java.awt.*;
import java.io.*;
import java.util.*;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import educover.backend.AccessControlService;
import educover.backend.UserSession;

/**
 *
 * @author Dyasi
 */

    
    public class EligibilityCheck extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EligibilityCheck.class.getName());
    private ArrayList<Student> students; 
    private JPanel studentListPanel;
    private AccessControlService access;


    /**
     * Creates new form EligibilityTest
     */
    public EligibilityCheck() {
        initComponents();
        
        
       
access = new AccessControlService(
        "src/data/Grades.txt",
        "src/data/Course_Information.txt",
        "src/data/Lecture_information.txt"
);

        students = new ArrayList<>();
        loadAndDisplayStudents(); // 
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BackToHome = new javax.swing.JButton();
        FilterButton = new javax.swing.JButton();
        ListOfStudents = new javax.swing.JScrollPane();
        AllowRegistrationButton = new javax.swing.JButton();
        EligibilityTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(null);
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        BackToHome.setBackground(new java.awt.Color(45, 59, 85));
        BackToHome.setForeground(new java.awt.Color(255, 255, 255));
        BackToHome.setText("Back to Home");
        BackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToHomeActionPerformed(evt);
            }
        });

        FilterButton.setBackground(new java.awt.Color(45, 59, 85));
        FilterButton.setForeground(new java.awt.Color(255, 255, 255));
        FilterButton.setText("Filter");
        FilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterButtonActionPerformed(evt);
            }
        });

        ListOfStudents.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        AllowRegistrationButton.setBackground(new java.awt.Color(45, 59, 85));
        AllowRegistrationButton.setForeground(new java.awt.Color(255, 255, 255));
        AllowRegistrationButton.setText("Allow Registration");
        AllowRegistrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllowRegistrationButtonActionPerformed(evt);
            }
        });

        EligibilityTitle.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        EligibilityTitle.setForeground(new java.awt.Color(45, 59, 85));
        EligibilityTitle.setText("Eligibility Check and Enrollment");

        jPanel2.setBackground(new java.awt.Color(45, 59, 85));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Name");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("StudentID");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Status");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CGPA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1170, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(131, 131, 131)
                .addComponent(jLabel4)
                .addGap(143, 143, 143))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AllowRegistrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListOfStudents)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BackToHome, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 387, Short.MAX_VALUE)
                        .addComponent(EligibilityTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 392, Short.MAX_VALUE)
                        .addComponent(FilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BackToHome, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EligibilityTitle)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListOfStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(AllowRegistrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        ListOfStudents.getAccessibleContext().setAccessibleParent(ListOfStudents);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToHomeActionPerformed
         if (UserSession.userID.startsWith("A")) {
            AdminHomePage adminHome  = new AdminHomePage();
            adminHome.setVisible(true);
            this.dispose();
            return;
        }
        
        HomePage home = new HomePage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackToHomeActionPerformed

    private void FilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterButtonActionPerformed
                                                     
    showFilterPopup();

    }//GEN-LAST:event_FilterButtonActionPerformed

    private void AllowRegistrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllowRegistrationButtonActionPerformed
  
     if (students.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No students loaded!", "Information", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    int count = 0;
    for (Student student : students) {
        if (student.isSelected && !student.isEnrolled) {
            enrollStudent(student);
            count++;
        }
    }

    if (count > 0) {
        saveEnrollments(); 
        saveStudentInformation();
        displayStudents();
        JOptionPane.showMessageDialog(this, count + " student(s) successfully enrolled!", "Enrollment Complete", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "No students selected or already enrolled!", "No Selection", JOptionPane.INFORMATION_MESSAGE);
    }


    }//GEN-LAST:event_AllowRegistrationButtonActionPerformed
private void saveStudentInformation() {
    File file = new File("src/data/Student_Information.txt");
    List<String> lines = new ArrayList<>();

    try (BufferedReader br = new BufferedReader(new FileReader(file))) {
        
        String header = br.readLine();
        lines.add(header);

        String line;
        while ((line = br.readLine()) != null) {
            String[] parts = line.split("\\|");
            if (parts.length < 6) {
                lines.add(line); 
                continue;
            }

            String studentID = parts[0].trim();
            Optional<Student> studentOpt = students.stream()
                .filter(s -> s.studentID.equals(studentID) && s.isEnrolled)
                .findFirst();

            if (studentOpt.isPresent()) {
                Student s = studentOpt.get();
                String[] names = s.fullName.split(" ", 2);
                String firstName = names.length > 0 ? names[0] : "";
                String lastName = names.length > 1 ? names[1] : "";

                
                lines.add(String.join("|",
                        s.studentID,
                        firstName,
                        lastName,
                        s.major,
                        s.year,
                        s.email
                ));
            } else {
                lines.add(line); 
            }
        }

    } catch (IOException e) {
        logger.log(Level.SEVERE, "Failed to read Student Information for saving", e);
        return;
    }

    
    try (PrintWriter pw = new PrintWriter(new FileWriter(file))) {
        for (String l : lines) {
            pw.println(l);
        }
    } catch (IOException e) {
        logger.log(Level.SEVERE, "Failed to save Student Information", e);
    }
}
    
    private void saveEnrollments() {
    File file = new File("src/data/Enrollment_Next_Sem.txt");
    try (PrintWriter pw = new PrintWriter(new FileWriter(file))) {
        for (Student s : students) {
            if (s.isEnrolled) {
                pw.println(s.studentID);
            }
        }
    } catch (IOException e) {
        logger.log(Level.SEVERE, "Failed to save enrollments", e);
    }
}

private void loadEnrollments() {
    File file = new File("src/data/Enrollment_Next_Sem.txt");
    if (!file.exists()) return;

    try (BufferedReader br = new BufferedReader(new FileReader(file))) {
        Set<String> enrolledIDs = new HashSet<>();
        String line;
        while ((line = br.readLine()) != null) {
            enrolledIDs.add(line.trim());
        }

        for (Student s : students) {
            if (enrolledIDs.contains(s.studentID)) {
                s.isEnrolled = true;
            }
        }
    } catch (IOException e) {
        logger.log(Level.SEVERE, "Failed to load enrollments", e);
    }
}

    
   private String getNextYear(String currentYear) {
    switch (currentYear.toLowerCase()) {
        case "freshman": return "Sophomore";
        case "sophomore": return "Junior";
        case "junior": return "Senior";
        default: return currentYear; 
    }
}
    
   private static final Map<String, String> majorMapping = Map.of(
    "Computer Science", "CS",
    "Statistics", "STAT",
    "History", "HIST",
    "Literature", "LIT",
    "Physics", "PHYS",
    "Biology", "BIO",
    "Mathematics", "MATH",
    "Economics", "ECON",
    "Philosophy", "PHIL",
    "English", "ENG"
);

private void enrollStudent(Student student) {
    student.isEnrolled = true;
    student.isSelected = false;

    
    student.year = getNextYear(student.year);

    
    Map<String, List<String>> curriculum = loadCurriculumForNextSem(majorMapping.getOrDefault(student.major, student.major));
    if (curriculum.containsKey(majorMapping.getOrDefault(student.major, student.major))) {
        for (String courseID : curriculum.get(majorMapping.getOrDefault(student.major, student.major))) {
            logger.info("Enrolled " + student.fullName + " in course: " + courseID);
        }
    }
}


private Map<String, List<String>> loadCurriculumForNextSem(String major) {
    Map<String, List<String>> map = new HashMap<>();
    File file = new File("src/data/Curriculum_Y1S2.txt");

    try (BufferedReader br = new BufferedReader(new FileReader(file))) {
        br.readLine(); 
        String line;

        while ((line = br.readLine()) != null) {
            String[] p = line.split("\\|");
            if (p.length < 2) continue;

            String majorID = p[0].trim();
            String courseID = p[1].trim();

            map.computeIfAbsent(majorID, k -> new ArrayList<>()).add(courseID);
        }

    } catch (Exception e) {
        logger.log(Level.SEVERE, "Curriculum load failed", e);
    }

    return map;
}
    
    public void loadAndDisplayStudents() {

    studentListPanel = new JPanel();
    studentListPanel.setLayout(new BoxLayout(studentListPanel, BoxLayout.Y_AXIS));
    studentListPanel.setBackground(Color.WHITE);

    ListOfStudents.setViewportView(studentListPanel);
    ListOfStudents.getVerticalScrollBar().setUnitIncrement(16);

    
    Map<String, Student> studentInfo = loadStudentInformation("src/data/Student_Information.txt");
    Map<String, CourseInfo> courseInfo = loadCourseInformation("src/data/Course_Information.txt");

    loadGrades("src/data/grades.txt", studentInfo, courseInfo);

   
students = new ArrayList<>(studentInfo.values());
computeEligibility();


String currentUser = UserSession.userID;  
boolean isAdmin = currentUser.startsWith("A");

if (!isAdmin) {
    List<String> allowedStudentIds = access.getAllowedStudents(currentUser);
   
    students.removeIf(s -> !allowedStudentIds.contains(s.studentID));
}

loadEnrollments();
displayStudents();
}
    
    private Map<String, Student> loadStudentInformation(String filename) {
        Map<String, Student> students = new LinkedHashMap<>();

        try (BufferedReader br = new BufferedReader(new FileReader(filename))) {
            br.readLine(); 
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split("\\|");

                if (parts.length >= 6) {
                    String studentID = parts[0].trim();
                    String fullName = parts[1].trim() + " " + parts[2].trim(); 
                    String major = parts[3].trim();
                    String year = parts[4].trim();
                    String email = parts[5].trim();

                    Student student = new Student(studentID, fullName, major, year, email);
                    students.put(studentID, student);
                }
            }

        } catch (IOException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error loading Student Information", e);
        }

        return students;
    }


    private Map<String, CourseInfo> loadCourseInformation(String filename) {
        Map<String, CourseInfo> map = new LinkedHashMap<>();

        try (BufferedReader br = new BufferedReader(new FileReader(filename))) {
            br.readLine();
            String line;

            while ((line = br.readLine()) != null) {
                String[] p = line.split("\\|");
                if (p.length != 6) continue;

                String id = p[0].trim();
                String name = p[1].trim();
                int credits = Integer.parseInt(p[2].trim());

                map.put(id, new CourseInfo(id, name, credits));
            }

        } catch (Exception e) {
             logger.log(java.util.logging.Level.SEVERE, "Error loading Course Information", e);
        }

        return map;
    }

    private void loadGrades(String filename, Map<String, Student> students, Map<String, CourseInfo> courses) {

        try (BufferedReader br = new BufferedReader(new FileReader(filename))) {
            br.readLine();
            String line;

            while ((line = br.readLine()) != null) {
                String[] p = line.split("\\|");
                if (p.length != 3) continue;

                String studentID = p[0].trim();
                String courseID = p[1].trim();
                double gpa = Double.parseDouble(p[2].trim());

                if (!students.containsKey(studentID)) continue;
                if (!courses.containsKey(courseID)) continue;

                CourseInfo info = courses.get(courseID);

                CourseGrade grade = new CourseGrade(courseID, gpa, info.credits);

                students.get(studentID).grades.put(courseID, grade);
            }

        } catch (Exception e) {
                 logger.log(java.util.logging.Level.SEVERE, "Error loading Grades", e);
        }
    }

    private void computeEligibility() {
        for (Student s : students) {
            
            double totalPoints = 0;
            int totalCredits = 0;
            int fails = 0;

            for (CourseGrade g : s.grades.values()) {
                totalCredits += g.credits;
                totalPoints += g.getGradePoints();

                if (g.gpa < 2.0)
                    fails++;
            }

            s.cgpa = (totalCredits > 0) ? totalPoints / totalCredits : 0.0;
            s.failedCourses = fails;

            
            s.isEligible = (s.cgpa >= 2.0 && s.failedCourses <= 3);
        }
    }

    /**
     * Displays all students in the panel
     */
    private void displayStudents() {

    studentListPanel.removeAll();

    String currentUser = UserSession.userID;
    boolean isAdmin = currentUser.startsWith("A");

    AccessControlService access = new AccessControlService(
            "src/data/Grades.txt",
            "src/data/Course_Information.txt",
            "src/data/Lecture_information.txt"
    );

    for (Student student : students) {

        if (isAdmin) {
            
            studentListPanel.add(new StudentRowPanel(student));
        } else {
            
            boolean canAccess = access.canLecturerAccess(currentUser, student.studentID);

            if (canAccess) {
                studentListPanel.add(new StudentRowPanel(student));
            }
        }
    }

    studentListPanel.revalidate();
    studentListPanel.repaint();
}

/**
 * Reads student data from CSV file and calculates CGPA
 *

     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EligibilityCheck().setVisible(true));
    }

    private void showFilterPopup() {
    
    JDialog filterDialog = new JDialog(this, "Filter Students", true);
    filterDialog.setSize(450, 350);
    filterDialog.setLocationRelativeTo(this);
    filterDialog.setLayout(new BorderLayout(15, 15));
    filterDialog.getContentPane().setBackground(Color.WHITE);

    
    JPanel paddingPanel = new JPanel();
    paddingPanel.setLayout(new BorderLayout(15, 15));
    paddingPanel.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));
    paddingPanel.setBackground(Color.WHITE);
    filterDialog.add(paddingPanel, BorderLayout.CENTER);

    
    JPanel searchPanel = new JPanel(new BorderLayout(5, 5));
    searchPanel.setBackground(Color.WHITE);

    JTextField searchField = new JTextField();
    searchField.setFont(new Font("Segoe UI", Font.PLAIN, 16));
    searchField.setPreferredSize(new Dimension(200, 60));
    searchField.setBorder(BorderFactory.createCompoundBorder(
            searchField.getBorder(),
            BorderFactory.createEmptyBorder(5, 5, 5, 5)
    ));

    searchPanel.add(searchField, BorderLayout.CENTER);
    paddingPanel.add(searchPanel, BorderLayout.NORTH);

    
    JPanel radioPanel = new JPanel(new GridLayout(3, 1, 10, 10));
    radioPanel.setBackground(Color.WHITE);
    radioPanel.setBorder(BorderFactory.createTitledBorder(
            BorderFactory.createLineBorder(new Color(200, 200, 200)),
            "Filter Options",
            javax.swing.border.TitledBorder.LEFT,
            javax.swing.border.TitledBorder.TOP,
            new Font("Segoe UI", Font.BOLD, 14)
    ));

    JRadioButton allBtn = new JRadioButton("All Students");
    JRadioButton enrolledBtn = new JRadioButton("Enrolled Students");
    JRadioButton eligibleBtn = new JRadioButton("Eligible Students");
    JRadioButton nonEligibleBtn = new JRadioButton("Non-Eligible Students");

    
    ButtonGroup group = new ButtonGroup();
    group.add(allBtn);
    group.add(enrolledBtn);
    group.add(eligibleBtn);
    group.add(nonEligibleBtn);
    allBtn.setSelected(true);

    Font rbFont = new Font("Segoe UI", Font.PLAIN, 14);
    allBtn.setFont(rbFont);
    enrolledBtn.setFont(rbFont);
    eligibleBtn.setFont(rbFont);
    nonEligibleBtn.setFont(rbFont);
    allBtn.setBackground(Color.WHITE);
    enrolledBtn.setBackground(Color.WHITE);
    eligibleBtn.setBackground(Color.WHITE);
    nonEligibleBtn.setBackground(Color.WHITE);

    radioPanel.add(allBtn);
    radioPanel.add(enrolledBtn);
    radioPanel.add(eligibleBtn);
    radioPanel.add(nonEligibleBtn);

    paddingPanel.add(radioPanel, BorderLayout.CENTER);

    
    JPanel bottomPanel = new JPanel();
    bottomPanel.setBackground(Color.WHITE);
    JButton applyBtn = new JButton("Apply Filter");
    applyBtn.setBackground(new Color(76, 175, 80));
    applyBtn.setForeground(Color.WHITE);
    applyBtn.setFont(new Font("Segoe UI", Font.BOLD, 14));
    applyBtn.setFocusPainted(false);
    applyBtn.setPreferredSize(new Dimension(150, 35));
    bottomPanel.add(applyBtn);

    paddingPanel.add(bottomPanel, BorderLayout.SOUTH);

    
    applyBtn.addActionListener(e -> {
        String searchText = searchField.getText().trim().toLowerCase();

        studentListPanel.removeAll();

        for (Student student : students) {
            boolean matchesSearch = student.fullName.toLowerCase().contains(searchText)
                    || student.studentID.toLowerCase().contains(searchText);

           boolean show = false;
if (allBtn.isSelected()) {
    show = matchesSearch;
} else if (eligibleBtn.isSelected()) {
    show = student.isEligible && !student.isEnrolled && matchesSearch;
} else if (nonEligibleBtn.isSelected()) {
    show = !student.isEligible && !student.isEnrolled && matchesSearch;
} else if (enrolledBtn.isSelected()) {
    show = student.isEnrolled && matchesSearch;
}

            if (show) {
                studentListPanel.add(new StudentRowPanel(student));
            }
        }

        studentListPanel.revalidate();
        studentListPanel.repaint();
        filterDialog.dispose();
    });

    filterDialog.setVisible(true);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AllowRegistrationButton;
    private javax.swing.JButton BackToHome;
    private javax.swing.JLabel EligibilityTitle;
    private javax.swing.JButton FilterButton;
    private javax.swing.JScrollPane ListOfStudents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}

class CourseInfo {
    String courseID;
    String courseName;
    int credits;
    
    public CourseInfo(String id, String name, int credits) {
        this.courseID = id;
        this.courseName = name;
        this.credits = credits;
    }
}

class CourseGrade {
    String courseID;
    double gpa;
    int credits;

    public CourseGrade(String courseID, double gpa, int credits) {
        this.courseID = courseID;
        this.gpa = gpa;
        this.credits = credits;
    }

    public double getGradePoints() {
        return gpa * credits;
    }
}

class Student {
    String studentID;
    String fullName;
    String major;
    String year;
    String email;

    Map<String, CourseGrade> grades = new LinkedHashMap<>();

    double cgpa;
    int failedCourses;
    boolean isEligible;
    boolean isSelected;

    boolean isEnrolled = false; 

    Student(String id, String name, String major, String year, String email) {
        this.studentID = id;
        this.fullName = name;
        this.major = major;
        this.year = year;
        this.email = email;
    }
}



class Lecture {
    String instructorID;
    String name;

    public Lecture(String id, String name) {
        this.instructorID = id;
        this.name = name;
    }

    public String getName() {
        return name;
    }
}


class CurriculumRow {
    String majorID;
    String courseID;

    public CurriculumRow(String majorID, String courseID) {
        this.majorID = majorID;
        this.courseID = courseID;
    }

    public String getMajorID() {
        return majorID;
    }

    public String getCourseID() {
        return courseID;
    }
}

/**
 * Custom panel that displays one student row with expandable details
 */
class StudentRowPanel extends JPanel {
    private JCheckBox checkBox;
    private JButton dropdownBtn;
    private JPanel detailsPanel;
    private JLabel statusLabel;
    private Student student;
    private boolean isExpanded = false;
    
    public StudentRowPanel(Student student) {
        this.student = student;

    if (student.isEnrolled) {
    statusLabel = new JLabel("✅ ENROLLED");
    statusLabel.setForeground(new Color(0, 128, 0));
} else if (student.isEligible) {
    statusLabel = new JLabel("✓ ELIGIBLE");
    statusLabel.setForeground(new Color(0, 128, 0));
} else {
    statusLabel = new JLabel("✗ NOT ELIGIBLE");
    statusLabel.setForeground(new Color(200, 0, 0));
}

    statusLabel.setFont(new Font("Arial", Font.BOLD, 16));

        setLayout(new BorderLayout());
        setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        
        
        Color bgColor;

if (student.isEnrolled) {
    bgColor = new Color(230, 240, 255); // light blue
} else if (student.isEligible) {
    bgColor = new Color(240, 255, 240); // light green
} else {
    bgColor = new Color(255, 240, 240); // light red
}
        setBackground(bgColor);
        
        setMaximumSize(new Dimension(Integer.MAX_VALUE, 60));
        setPreferredSize(new Dimension(1810, 60));
        
        
        JPanel mainRow = new JPanel(new BorderLayout(10, 0));
        mainRow.setBackground(bgColor);
        mainRow.setBorder(BorderFactory.createEmptyBorder(10, 15, 10, 15));
        
    
        JPanel leftPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 15, 0));
        leftPanel.setBackground(bgColor);
        
        JLabel nameLabel = new JLabel(student.fullName);
        nameLabel.setFont(new Font("Arial", Font.BOLD, 18));

        JLabel idLabel = new JLabel(String.format("(%s)", student.studentID));
        idLabel.setFont(new Font("Arial", Font.PLAIN, 16));
        idLabel.setForeground(Color.GRAY);
        
        leftPanel.add(nameLabel);
        leftPanel.add(idLabel);
        
        
        JPanel rightPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT, 15, 0));
        rightPanel.setBackground(bgColor);
        
        
        
JLabel cgpaLabel;

if (student.isEnrolled) {
    cgpaLabel = new JLabel("CGPA: 0.00");
    cgpaLabel.setForeground(new Color(70, 130, 180)); // Steel Blue
} else {
    cgpaLabel = new JLabel(String.format("CGPA: %.2f", student.cgpa));
    cgpaLabel.setForeground(Color.BLACK);
}

cgpaLabel.setFont(new Font("Arial", Font.PLAIN, 18));

        
        
        JLabel failedLabel = new JLabel(String.format("Failed: %d", student.failedCourses));
        failedLabel.setFont(new Font("Arial", Font.PLAIN, 16));
        failedLabel.setForeground(student.failedCourses > 3 ? Color.RED : Color.GRAY);
        
        
        dropdownBtn = new JButton("▼");
        dropdownBtn.setFont(new Font("Arial", Font.PLAIN, 16));
        dropdownBtn.setPreferredSize(new Dimension(50, 35));
        dropdownBtn.setFocusPainted(false);
        dropdownBtn.addActionListener(e -> toggleDetails());
        
        
       
        checkBox = new JCheckBox();
checkBox.setBackground(bgColor);
checkBox.setPreferredSize(new Dimension(30, 30));
checkBox.setEnabled(student.isEligible && !student.isEnrolled); 
checkBox.setSelected(student.isSelected); 
checkBox.addActionListener(e -> student.isSelected = checkBox.isSelected());
        
        rightPanel.add(statusLabel);
        rightPanel.add(failedLabel);
        rightPanel.add(cgpaLabel);
        rightPanel.add(dropdownBtn);
        rightPanel.add(checkBox);
        
        mainRow.add(leftPanel, BorderLayout.WEST);
        mainRow.add(rightPanel, BorderLayout.EAST);
        
        
        detailsPanel = new JPanel();
        detailsPanel.setLayout(new BoxLayout(detailsPanel, BoxLayout.Y_AXIS));
        detailsPanel.setBackground(new Color(245, 245, 245));
        detailsPanel.setBorder(BorderFactory.createEmptyBorder(15, 30, 15, 30));
        detailsPanel.setVisible(false);
        
        
        addDetailRow("Major:", student.major);
        addDetailRow("Year:", student.year);
        addDetailRow("Email:", student.email);
        
        detailsPanel.add(Box.createVerticalStrut(10));
        
        
        JLabel coursesHeader = new JLabel("Course Grades:");
        coursesHeader.setFont(new Font("Arial", Font.BOLD, 16));
        coursesHeader.setAlignmentX(Component.LEFT_ALIGNMENT);
        detailsPanel.add(coursesHeader);
        detailsPanel.add(Box.createVerticalStrut(8));
        
        JLabel sem1Label = new JLabel("Semester 1:");
        sem1Label.setFont(new Font("Arial", Font.BOLD, 14));
        sem1Label.setAlignmentX(Component.LEFT_ALIGNMENT);
        detailsPanel.add(sem1Label);
        detailsPanel.add(Box.createVerticalStrut(5));

        
        
        for (Map.Entry<String, CourseGrade> entry : student.grades.entrySet()) {
        CourseGrade cg = entry.getValue();
        String courseName = entry.getKey(); 

        JLabel courseLabel = new JLabel(String.format("   • %s: %.1f GPA (%d credits)", 
            courseName, cg.gpa, cg.credits));
        courseLabel.setFont(new Font("Arial", Font.PLAIN, 15));
        courseLabel.setAlignmentX(Component.LEFT_ALIGNMENT);

    
        if (cg.gpa < 2.0) {
            courseLabel.setForeground(Color.RED);
        }

        detailsPanel.add(courseLabel);
        detailsPanel.add(Box.createVerticalStrut(5));
    }

        if (student.isEnrolled) {
    detailsPanel.add(Box.createVerticalStrut(10));

    JLabel sem2Label = new JLabel("Semester 2:");
    sem2Label.setFont(new Font("Arial", Font.BOLD, 14));
    sem2Label.setAlignmentX(Component.LEFT_ALIGNMENT);
    detailsPanel.add(sem2Label);

    JLabel sem2GpaLabel = new JLabel("   • GPA: 0.00");
    sem2GpaLabel.setFont(new Font("Arial", Font.PLAIN, 15));
    sem2GpaLabel.setForeground(new Color(70, 130, 180)); 
    sem2GpaLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
    detailsPanel.add(sem2GpaLabel);
}

        
       
        detailsPanel.add(Box.createVerticalStrut(10));
        JLabel cgpaCalc = new JLabel(String.format("Calculated CGPA: %.2f", student.cgpa));
        cgpaCalc.setFont(new Font("Arial", Font.BOLD, 15));
        cgpaCalc.setAlignmentX(Component.LEFT_ALIGNMENT);
        detailsPanel.add(cgpaCalc);
        
        add(mainRow, BorderLayout.NORTH);
        add(detailsPanel, BorderLayout.CENTER);
    }
    
    private void addDetailRow(String label, String value) {
        JLabel detailLabel = new JLabel(String.format("%s %s", label, value));
        detailLabel.setFont(new Font("Arial", Font.PLAIN, 14));
        detailLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
        detailsPanel.add(detailLabel);
        detailsPanel.add(Box.createVerticalStrut(5));
    }
    
    private void toggleDetails() {
        isExpanded = !isExpanded;
        detailsPanel.setVisible(isExpanded);
        dropdownBtn.setText(isExpanded ? "▲" : "▼");
        
        if (isExpanded) {
            int detailsHeight = detailsPanel.getPreferredSize().height;
            setMaximumSize(new Dimension(Integer.MAX_VALUE, 60 + detailsHeight));
            setPreferredSize(new Dimension(1810, 60 + detailsHeight));
        } else {
            setMaximumSize(new Dimension(Integer.MAX_VALUE, 60));
            setPreferredSize(new Dimension(1810, 60));
        }
        
        revalidate();
        repaint();
        
       
        Container parent = getParent();
        if (parent != null) {
            parent.revalidate();
            parent.repaint();
        }
    }
    
    public boolean isSelected() {
        return checkBox.isSelected();
    }
    
    public Student getStudent() {
        return student;
    }
    

public boolean isCheckboxEnabled() {
    return checkBox.isEnabled();
}

public void markAsEnrolled() {
    checkBox.setSelected(false);
    checkBox.setEnabled(false);
    statusLabel.setText("✅ ENROLLED");
    statusLabel.setForeground(new Color(0, 153, 0));
}

public void disableCheckbox() {
    student.isSelected = false;
    student.isEnrolled = true; 
    checkBox.setSelected(false);
    checkBox.setEnabled(false);
    statusLabel.setText("✅ ENROLLED");
    statusLabel.setForeground(new Color(0, 128, 0));
}

}

