/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package educover;

import educover.backend.GenerateOTP;
import educover.backend.JavaMailAPI;
import educover.backend.UserSession;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JOptionPane;

/**
 *
 * @author aizik
 */
public class RecoverPassword extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RecoverPassword.class.getName());
    private static final String LectureFilePath = "src/Data/Lecture_information.txt";
    /**
     * Creates new form RecoverPassword
     */
    public RecoverPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        leftSide = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rightSide = new javax.swing.JPanel();
        revocerPasswordEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RequestOTPButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));

        leftSide.setBackground(new java.awt.Color(75, 100, 146));
        leftSide.setMaximumSize(new java.awt.Dimension(960, 1080));
        leftSide.setMinimumSize(new java.awt.Dimension(960, 1080));
        leftSide.setPreferredSize(new java.awt.Dimension(960, 1080));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Educover_logo/EduCoverLogo.png"))); // NOI18N

        javax.swing.GroupLayout leftSideLayout = new javax.swing.GroupLayout(leftSide);
        leftSide.setLayout(leftSideLayout);
        leftSideLayout.setHorizontalGroup(
            leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftSideLayout.createSequentialGroup()
                .addContainerGap(223, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(237, 237, 237))
        );
        leftSideLayout.setVerticalGroup(
            leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSideLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jLabel4)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        revocerPasswordEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        revocerPasswordEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revocerPasswordEmailActionPerformed(evt);
            }
        });
        revocerPasswordEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                revocerPasswordEmailKeyPressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(75, 100, 146));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Oops Forgot Your Password ?");
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 64));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 64));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Email Address");

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Enter your email to resive an OTP for password reset");

        RequestOTPButton.setBackground(new java.awt.Color(45, 59, 85));
        RequestOTPButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RequestOTPButton.setForeground(new java.awt.Color(255, 255, 255));
        RequestOTPButton.setText("Request OTP");
        RequestOTPButton.setMaximumSize(new java.awt.Dimension(94, 39));
        RequestOTPButton.setMinimumSize(new java.awt.Dimension(94, 39));
        RequestOTPButton.setPreferredSize(new java.awt.Dimension(94, 39));
        RequestOTPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestOTPButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightSideLayout = new javax.swing.GroupLayout(rightSide);
        rightSide.setLayout(rightSideLayout);
        rightSideLayout.setHorizontalGroup(
            rightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
            .addGroup(rightSideLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(rightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RequestOTPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(revocerPasswordEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rightSideLayout.setVerticalGroup(
            rightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightSideLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(59, 59, 59)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(revocerPasswordEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(RequestOTPButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(626, Short.MAX_VALUE))
        );

        revocerPasswordEmail.getAccessibleContext().setAccessibleName("revocerPasswordEmail");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(leftSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rightSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void revocerPasswordEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_revocerPasswordEmailKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            RequestOTPButtonActionPerformed(null);
        }
    }//GEN-LAST:event_revocerPasswordEmailKeyPressed

    private void RequestOTPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestOTPButtonActionPerformed
    String userEmail = revocerPasswordEmail.getText().trim();

    File lectureData = new File(LectureFilePath);
    boolean emailFound = false;

    try (BufferedReader br = new BufferedReader(new FileReader(lectureData))) {
        String line;

        while ((line = br.readLine()) != null) {
            String[] parts = line.split("\\|");

            if (parts.length == 5) {
                String fileEmail = parts[2];

                if (fileEmail.equalsIgnoreCase(userEmail)) {
                    emailFound = true;

                    // generate OTP
                    String otp = GenerateOTP.generateOTPNumber();
                    UserSession.OTP = otp;   // store OTP (optional)
                    UserSession.userEmail = userEmail;
                    
                    String subject = "Password Reset OTP for EduCover";
                    String message = "Here is your one-time OTP: " + "(" +otp + ")" + " If you did not request this, Please Ingore this Email";

                    // send email
                    JavaMailAPI.sendEmail(userEmail, subject, message);
                    
                    VerifyOTP verify = new VerifyOTP();
                    verify.setVisible(true);
                    this.dispose();
                    
                    JOptionPane.showMessageDialog(this,
                        "OTP has been sent to your email.",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);

                    break;
                }
            }
        }

        if (!emailFound) {
            JOptionPane.showMessageDialog(this,
                "Email not found. Please enter a valid email address.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "An error occurred: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_RequestOTPButtonActionPerformed

    private void revocerPasswordEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revocerPasswordEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_revocerPasswordEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RecoverPassword().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RequestOTPButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel leftSide;
    private javax.swing.JTextField revocerPasswordEmail;
    private javax.swing.JPanel rightSide;
    // End of variables declaration//GEN-END:variables
}
