/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package educover;


import educover.backend.FillLectureTable;
import educover.backend.RemoveUser;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author aizik
 */
public class UserManagement extends javax.swing.JFrame {
    
    private static final String LectureFilePath = "src/Data/Lecture_information.txt";
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserManagement.class.getName());
    
    

    /**
     * Creates new form UserManagement
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    public UserManagement(){
        initComponents();
        
        setTitle("User Management");
        setSize(800,400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        loadLectureData();
    }
    
    private void setLectureTableColumnWidths() {
        var cm = lectureTable.getColumnModel();
        cm.getColumn(0).setPreferredWidth(100); // Lecture ID
        cm.getColumn(1).setPreferredWidth(200); // Name
        cm.getColumn(2).setPreferredWidth(180); // Email
        cm.getColumn(3).setPreferredWidth(150); // Department
        cm.getColumn(4).setPreferredWidth(100); // Status
    }

    private void setupStatusDropdown() {

    String[] statuses = {"Active", "Suspended", "Deactivated"};
        javax.swing.JComboBox<String> statusCombo =
            new javax.swing.JComboBox<>(statuses);

        lectureTable.getColumnModel()
                    .getColumn(4) // Status column
                    .setCellEditor(new javax.swing.DefaultCellEditor(statusCombo));
    }
    
    private void loadLectureData(){ //Puts all the info in to the table 
        
        try {
            DefaultTableModel model = FillLectureTable.getLectureTableInformation(LectureFilePath);
            lectureTable.setModel(model);
            setLectureTableColumnWidths();
            setupStatusDropdown();
            addStatusChangeListener();
        }catch (IOException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error reading lecture data file.");
        }
        
        lectureTable.getModel().addTableModelListener(e -> {
    if (e.getType() == javax.swing.event.TableModelEvent.UPDATE) {

        int row = e.getFirstRow();
        int col = e.getColumn();

        if (col == 4) { // Status column
            DefaultTableModel model =
                    (DefaultTableModel) lectureTable.getModel();

            String userId = model.getValueAt(row, 0).toString();
            String newStatus = model.getValueAt(row, 4).toString();

            System.out.println(
                "Status changed -> User: " + userId + ", New Status: " + newStatus
            );

            // Later: updateStatusInFile(userId, newStatus);
        }
    }
});
        
    }
    
    private void addStatusChangeListener() {

    lectureTable.getModel().addTableModelListener(e -> {

        if (e.getType() == javax.swing.event.TableModelEvent.UPDATE) {

            int row = e.getFirstRow();
            int col = e.getColumn();

            if (col == 4) { // Status column
                DefaultTableModel model =
                        (DefaultTableModel) lectureTable.getModel();

                String userId = model.getValueAt(row, 0).toString();
                String newStatus = model.getValueAt(row, 4).toString();

                System.out.println(
                    "Status changed -> User: " + userId + ", New Status: " + newStatus
                );

                // updateStatusInFile(userId, newStatus);
            }
        }
    });
}

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lectureTable = new javax.swing.JTable();
        EditUser = new javax.swing.JButton();
        AddNewUser = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Delete = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("User Management");

        lectureTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "User ID", "Email", "Name", "Role", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lectureTable.setRowHeight(30);
        lectureTable.setShowGrid(true);
        jScrollPane1.setViewportView(lectureTable);

        EditUser.setText("Edit User");
        EditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditUserActionPerformed(evt);
            }
        });

        AddNewUser.setText("Add New User");
        AddNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewUserActionPerformed(evt);
            }
        });

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1743, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(AddNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(529, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 926, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditUserActionPerformed
        int selectedRow = lectureTable.getSelectedRow();
        
        if (selectedRow == -1 ){
            JOptionPane.showMessageDialog(this, "Please select a user to edit");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel)lectureTable.getModel();
        String userID = model.getValueAt(selectedRow,0).toString();
        
        
        EditStaffInfo editPanel = new EditStaffInfo(userID);
        editPanel.setVisible(true);
        editPanel.setLocationRelativeTo(null);
    }//GEN-LAST:event_EditUserActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        AdminHomePage home = new AdminHomePage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void AddNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewUserActionPerformed
        AddNewUser newUser = new AddNewUser();
        newUser.setVisible(true);
        newUser.setLocationRelativeTo(null);
    }//GEN-LAST:event_AddNewUserActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
    int selectedRow = lectureTable.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a user to delete");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this user?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) return;

    DefaultTableModel model = (DefaultTableModel) lectureTable.getModel();
    String userId = model.getValueAt(selectedRow, 0).toString();

    boolean success = RemoveUser.deleteUserFromFile(userId);

    if (success) {
        JOptionPane.showMessageDialog(this, "User deleted successfully");
        loadLectureData();
    } else {
        JOptionPane.showMessageDialog(this, "Failed to delete user");
    }
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserManagement().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewUser;
    private javax.swing.JButton Back;
    private javax.swing.JButton Delete;
    private javax.swing.JButton EditUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable lectureTable;
    // End of variables declaration//GEN-END:variables
}
